# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5144321fe3af9977cf0246fd68ca7748704d701ff1c7f498e1caf8039a34cf745bea21c461865ab528b8d27acc15a4055bc63d8d7104e9586690d9ab1c8db577

test:
  secret_key_base: 1e2bb14643f89c077fa13a7e4e4c6f5701803ec8433a95ecdee8efd530d002cc7b8e9edaf89b00733d3e3ec0bd5631aad43dd21ff249acf7aee078f6228bbada

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
